'use strict';

module.exports = [
  {
    id: 'shaadi',
    name: 'Shaadi',
    description: 'Music for every moment of an Indian wedding celebration.',
    icon: '💍',
    accent: '#d4a017',
    background: '#241b12',
    queries: [
      'shaadi sangeet dance song',
      'mehndi ceremony song',
      'baraat music',
      'haldi ceremony song',
      'indian wedding instrumental',
    ],
    searchable: false,
  },
  {
    id: 'devotional',
    name: 'Devotional',
    description: 'Bhajans, aartis, and devotional music.',
    icon: '🪔',
    accent: '#e07a5f',
    background: '#261713',
    queries: [
      'bhajan devotional song',
      'kirtan live',
      'ganesh aarti',
      'hanuman chalisa',
      'morning temple bhajan',
    ],
    searchable: false,
  },
  {
    id: 'focus',
    name: 'Focus',
    description: 'Quiet sounds for study and deep work.',
    icon: '🎧',
    accent: '#4a90e2',
    background: '#111b2a',
    queries: [
      'lofi hip hop study',
      'ambient focus music',
      'instrumental concentration',
      'alpha waves study',
      'deep work music',
    ],
    searchable: false,
  },
  {
    id: 'late-night',
    name: 'Late Night',
    description: 'After-hours synths, chillhop, and mellow electronic sounds.',
    icon: '🌙',
    accent: '#7b68ee',
    background: '#171327',
    queries: [
      'synthwave drive',
      'chillhop night',
      'retrowave night',
      'mellow electronic night',
      'midnight city music',
    ],
    searchable: false,
  },
  {
    id: 'monsoon',
    name: 'Monsoon',
    description: 'Rainy-day listening, from cozy lofi to classic melodies.',
    icon: '🌧️',
    accent: '#5c8a8a',
    background: '#142020',
    queries: [
      'rainy day lofi',
      'monsoon instrumental',
      'rain with music',
      'monsoon bollywood classics',
      'cozy rain music',
    ],
    searchable: false,
  },
  {
    id: 'workout',
    name: 'Workout',
    description: 'High-energy tracks to keep you moving.',
    icon: '💪',
    accent: '#e63946',
    background: '#261416',
    queries: [
      'workout motivation music',
      'gym phonk',
      'hardstyle workout',
      'hip hop gym mix',
      'cardio electronic',
    ],
    searchable: false,
  },
  {
    id: 'appana-gana',
    name: 'Appana Gana',
    description: 'Find and save the music you love.',
    icon: '🎵',
    accent: '#9d4edd',
    background: '#21142b',
    queries: [],
    searchable: true,
  },
];
